spring:
  data.neo4j.database: neo4j
  security:
    user:
      name: user
      password: password
  # Default values for local database connection, can be overridden by environment variables
  neo4j:
    authentication:
      username: ${DB_USERNAME:neo4j}
      password: ${DB_PASSWORD:password}
    uri: ${DB_URI:'bolt://localhost:7687'}

logging:
  level:
    org:
      springframework:
        web: debug
        filter:
          CommonsRequestLoggingFilter: debug
        data:
          neo4j: debug