spring:
  data.neo4j.database: neo4j
  security:
    user:
      name: user
      password: password
  neo4j:
    authentication:
      username: neo4j
      password: password
    uri: bolt://localhost:7687

logging:
  level:
    org:
      springframework:
        web: debug
        filter:
          CommonsRequestLoggingFilter: debug
        data:
          neo4j: debug